name: tracking-remove-tag

on:
  delete:
    branches: [ vanchonlee-patch-1 ]
    tag:
      - '*'
jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "asdf"
