name: tracking-remove-tag

on:
  delete:
    tags:
      - '*'
jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Get information
        id: infor
        run: |
          echo "::set-output name=user::$(jq '.actor' $GITHUB_CONTEXT)\n"
          echo "::set-output name=tag_name::$(jq '.event.ref' $GITHUB_CONTEXT)\n"
          echo "::set-output name=delete_time::$(jq '.event.repository.pushed_at' $GITHUB_CONTEXT)\n"
